# Generated by Django 4.2.24 on 2026-05-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '11499_add_editlog_resourceinstance_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(max_length=254)),
                ('external_reference_type', models.SlugField(max_length=128)),
                ('related_resourceinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='models.resourceinstance')),
            ],
            options={
                'unique_together': {('external_reference', 'external_reference_type')},
            },
        ),
    ]
